spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: tndus28901@gmail.com
      password: ouanwbzpmdrtfbve
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true


server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 8000


