spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: tndus28901@gmail.com
      password: ouanwbzpmdrtfbve
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true